version: '3.4'

services:
  # valorant-women-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - TYPEORM_HOST=myproject://sql
  #     - TYPEORM_USERNAME=SA
  #     - TYPEORM_PASSWORD=<YourStrong@Passw0rd>
  #   networks:
  #     - service
  #   depends_on:
  #     - sql

  sql:
    build:
      context: sql
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    networks:
      - service

networks:
  service:
