version: '3.4'

services:
  api:
    build:
      context: service
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3002
      - TYPEORM_HOST=http://sql
      - TYPEORM_PORT=1433
      - TYPEORM_USERNAME=SA
      - TYPEORM_PASSWORD=<YourStrong@Passw0rd>
      - TYPEORM_DATABASE=womanofvalorant
    ports:
      - "3002:3002"
    networks:
      - service
    depends_on:
      - sql

  sql:
    build:
      context: sql
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=<YourStrong@Passw0rd>
    ports:
      - "1433:1433"
    networks:
      - service

networks:
  service:
