version: '3.4'

services:
  client:
    build:
      context: client-remix
      dockerfile: Dockerfile
    environment:
      - PORT=${CLIENT_PORT}
      - DAPR_HTTP_PORT=${DAPR_HTTP_PORT}
      - API_URL=http://host.docker.internal:${API_PORT}
      - AUTH0_RETURN_TO_URL=${AUTH0_RETURN_TO_URL}
      - AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_MANAGEMENT_APP_CLIENT_ID=${AUTH0_MANAGEMENT_APP_CLIENT_ID}
      - AUTH0_MANAGEMENT_APP_CLIENT_SECRET=${AUTH0_MANAGEMENT_APP_CLIENT_SECRET}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_LOGOUT_URL=${AUTH0_LOGOUT_URL}
      - COOKIE_SECRET=${COOKIE_SECRET}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    networks:
      - valorantnetwork

  client-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "client",
      "-app-port", "${CLIENT_PORT}",
      "-dapr-http-port", "${DAPR_HTTP_PORT}",
      "-log-level", "debug",
      "-components-path", "./components"]
    depends_on:
      - client

  api:
    build:
      context: service
      dockerfile: Dockerfile
    environment:
      - HOST=${API_HOST}
      - PORT=${API_PORT}
      - DAPR_HOST=${DAPR_HOST}
      - DAPR_HTTP_PORT=${DAPR_HTTP_PORT}
      - COSMOSDB_ACCOUNT=${COSMOSDB_ACCOUNT}
      - COSMOSDB_KEY=${COSMOSDB_KEY}
      - COSMOSDB_DATABASE_ID=${COSMOSDB_DATABASE_ID}
      - COSMOSDB_CONTAINER_ID=${COSMOSDB_CONTAINER_ID}
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - valorantnetwork

  api-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "api",
      "-app-port", "${API_PORT}",
      "-dapr-http-port", "${API_PORT}",
      "-log-level", "debug",
      "-components-path", "./components"]
    volumes:
        - "./components/:/components"
        - "./secrets/:/secrets"
    depends_on:
      - api

networks:
  valorantnetwork:
