POST http://localhost:3002/ratings
Accept: application/json
Content-Type: application/json

{
    "userName": "Matt",
    "rankedAgentNames": [
        "PlayerOne",
        "PlayerOne",
        "PlayerOne",
        "PlayerOne",
        "PlayerOne",
        "PlayerOne",
        "PlayerOne"
    ]
}