POST http://localhost:3002/ratings
Accept: application/json
Content-Type: application/json

{
    "userName": "Matt",
    "isWomen": true,
    "rankedAgentNames": [
        "jett",
        "killjoy",
        "skye",
        "raze",
        "sage",
        "reyna",
        "viper"
    ]
}