FROM mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

EXPOSE 1433

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=<YourStrong@Passw0rd>

EXPOSE 1433

# CMD /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "<YourStrong@Passw0rd>"

